### ISSUE TITLE
Memory access problem in rtpsources.cpp line 339

### ISSUE THREAD

**Issue by lbakman** [j0r1/JRTPLIB#4]
Hi Jori

I believe I have found a memory access problem in rtpsources.cpp line 339, if a session implementation overrides OnValidatedRTPPacket, sets ispackethandled to true and deletes the RTPPacket pointer.

In rtpsources.cpp line 232 srcdat->ProcessRTPPacket is called, which in turn calls OnValidatedRTPPacket. In example6 the override deletes the packet using DeletePacket(packet), but in rtpsources.cpp line 339, rtppack->GetCSRCCount() is called on a deleted object and in line rtppack->GetCSRC(i) may be called on the same deleted object.

I do not have a suggestion for a fix, but either the OnValidatedRTPPacket should not delete the packet, or it should be handled in some other way. If OnValidatedRTPPacket deletes the packet, the entire contributing source handling will be broken.

I can just avoid setting ispackethandled to true and delete the packet, but that means that the packets are stored in the packetlist and I am not sure why I would want that (I call Poll() from my own thread as in example8).

Regards 
Lau Bakman

**Comment by j0r1** [comment]
Hi Lau,

You're correct, this is indeed a problem.

I think the easiest fix would be to cache the CSRCs temporarily, before the srcdat->ProcessRTPPacket function is called, and then use those cached values further on (instead of obtaining them from rtppack)

This is what I tried to do in branch ['csrccache'](https://github.com/j0r1/JRTPLIB/commit/bf0c7827b102b0edf4959dac622a70fc5dfa31df) - I haven't tested it though. Could you check if this works for you?

Thanks!
Jori

**Comment by lbakman** [comment]
Hi Jori

That seems to have fixed the problem when running example 6 with valgrind. 

I will do some more testing with my own project today and let you know.

Thank you for the fast response.

Lau

**Comment by lbakman** [comment]
Hi Jori

I have not found any issues with your fix in the csrccache branch except for the potential problem I mentioned above.

Regards
Lau

**Comment by j0r1** [comment]
Hi Lau,

The number of CSRCs comes from four bits in the RTP header, so it shouldn't exceed that maximum number. But it's probably best to be extra cautious, so I've added an extra check.

Thanks for testing!

Cheers,
Jori
